---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IAMRoleEc2Default:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2-Default
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
  
  IAMProfileEc2DefaultInstance:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2-Default
      Roles:
        - !Ref IAMRoleEc2Default

  IAMRoleEc2Bastion:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2-Bastion
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - !Ref IAMPolicyEc2AllowModifyInstanceAttiribute
        - !Ref IAMPolicyEc2AllowModifyInstanceMetadataOptions
  IAMEc2ProfileBastionInstance:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2-Bastion
      Roles:
        - !Ref IAMRoleEc2Bastion
  IAMPolicyEc2AllowModifyInstanceAttiribute:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Custom-EC2AllowModifyInstanceAttribute
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowModifyInstanceAttribute
            Effect: Allow
            Action: ec2:ModifyInstanceAttribute
            Resource: "*"
  IAMPolicyEc2AllowModifyInstanceMetadataOptions:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Custom-EC2AllowModifyInstanceMetadataOptions
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowModifyInstanceAttribute
            Effect: Allow
            Action: ec2:ModifyInstanceMetadataOptions
            Resource: "*"

  IAMRoleRDSEnhancedMonitor:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RDS-EnhancedMonitor
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
Outputs:
  IAMRoleEc2Default:
    Value: !Ref IAMProfileEc2DefaultInstance
    Export:
      Name: IAM-Ec2ProfileDefaultInstance
  IAMRoleEc2Bastion:
    Value: !Ref IAMEc2ProfileBastionInstance
    Export:
      Name: IAM-Ec2ProfiletBastionInstance
  IAMRoleRDSEnhancedMonitorArn:
    Value: !GetAtt IAMRoleRDSEnhancedMonitor.Arn
    Export:
      Name: IAM-RoleRDSEnhancedMonitorArn