---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TenchoLabNetHostName:
    Type: String
    Default: tencho-lab.net
  AwsTenchoLabNetHostName:
    Type: String
    Default: aws.tencho-lab.net
  NorikiMeHostName:
    Type: String
    Default: noriki.me

Resources:
  TenchoLabNetHostZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref TenchoLabNetHostName
  TenchoLabNetPrivateHostZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref TenchoLabNetHostName
      VPCs:
        - VPCId: !ImportValue VPC-Id
          VPCRegion: ap-northeast-1
  AwsTenchoLabNetHostZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref AwsTenchoLabNetHostName
  NorikiMeHostZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref NorikiMeHostName

Outputs:
  TenchoLabNetHostZoneId:
    Value: !Ref TenchoLabNetHostZone
    Export:
      Name: Route53-TenchoLabNetHostZoneId
  TenchoLabNetPrivateHostZoneId:
    Value: !Ref TenchoLabNetPrivateHostZone
    Export:
      Name: Route53-TenchoLabNetPrivateHostZoneId
  AwsTenchoLabNetHostZoneId:
    Value: !Ref AwsTenchoLabNetHostZone
    Export:
      Name: Route53-AwsTenchoLabNetHostZoneId
  NorikiMeHostZoneId:
    Value: !Ref NorikiMeHostZone
    Export:
      Name: Route53-NorikiMeHostZoneId