---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IAMRoleEc2Default:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2-Default
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
  
  IAMProfileEc2DefaultInstance:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2-Default
      Roles:
