---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SystemName:
    Type: String
    Default: Blog
Resources:
  BlogWAF:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Ref SystemName
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: True
        CloudWatchMetricsEnabled: True
        MetricName: !Ref SystemName
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: AWS-AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: False
        - Name: AWS-AWSManagedRulesLinuxRuleSet
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: AWS-AWSManagedRulesLinuxRuleSet
            SampledRequestsEnabled: False
        - Name: AWS-AWSManagedRulesPHPRuleSet
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesPHPRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: AWS-AWSManagedRulesPHPRuleSet
            SampledRequestsEnabled: False
        - Name: AWS-AWSManagedRulesSQLiRuleSet
          Priority: 4
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: AWS-AWSManagedRulesSQLiRuleSet
            SampledRequestsEnabled: False
        - Name: AWS-AWSManagedRulesWordPressRuleSet
          Priority: 5
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesWordPressRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: AWS-AWSManagedRulesWordPressRuleSet
            SampledRequestsEnabled: False