---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  BlogECRWordpress:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: blog/wordpress
      ImageScanningConfiguration:
        ScanOnPush: True
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete unncessary images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
Outputs: 
  ECRWordpressName:
    Value: !Ref BlogECRWordpress
  ECRWordpressUri:
    Value: !GetAtt BlogECRWordpress.RepositoryUri