---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SystemName:
    Type: String
  CodePipelineServiceRoleArn:
    Type: String
  S3Name:
    Type: String
  CodeCommitRepositoryName:
    Type: String
  CodeBuildContainerImage:
    Type: String
Resources:
  BlogCodePipelineContainerImage:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${SystemName}-ContainerImage
      RoleArn: !Ref CodePipelineServiceRoleArn
      ArtifactStore:
        Location: !Ref S3Name
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: !Ref CodeCommitRepositoryName
                BranchName: main
              Namespace: SourceaVariables
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuildContainerImage
              Namespace: BuildVariables
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1