---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ELBHostOriginFqdn:
    Type: String
  ELBHostProdFqdn:
    Type: String
  ELBDnsName:
    Type: String
  ELBCanonicalHostedZoneID:
    Type: String
  CloudFrontDnsName:
    Type: String
  CloudFrontImgDnsName:
    Type: String
Resources:
  BlogRoute53OriginHost:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      Name: !Ref ELBHostOriginFqdn
      HostedZoneId: !ImportValue Route53-AwsTenchoLabNetHostZoneId
      AliasTarget:
        DNSName: !Ref ELBDnsName
        HostedZoneId: !Ref ELBCanonicalHostedZoneID

  # blog.tencho-lab.net from PrivateZone is Associated by other stack ?(maybe)
  BlogRoute53ProdHost:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      Name: !Ref ELBHostProdFqdn
      HostedZoneId: !ImportValue Route53-TenchoLabNetHostZoneId
      AliasTarget:
        DNSName: !Ref CloudFrontDnsName
        HostedZoneId: Z2FDTNDATAQYW2
  BlogRoute53ProdHostAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: AAAA
      Name: !Ref ELBHostProdFqdn
      HostedZoneId: !ImportValue Route53-TenchoLabNetHostZoneId
      AliasTarget:
        DNSName: !Ref CloudFrontDnsName
        HostedZoneId: Z2FDTNDATAQYW2
  BlogImgRoute53ProdHost:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      Name: !Sub img.${ELBHostProdFqdn}
      HostedZoneId: !ImportValue Route53-TenchoLabNetHostZoneId
      AliasTarget:
        DNSName: !Ref CloudFrontImgDnsName
        HostedZoneId: Z2FDTNDATAQYW2
  BlogImgRoute53ProdHostAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: AAAA
      Name: !Sub img.${ELBHostProdFqdn}
      HostedZoneId: !ImportValue Route53-TenchoLabNetHostZoneId
      AliasTarget:
        DNSName: !Ref CloudFrontImgDnsName
        HostedZoneId: Z2FDTNDATAQYW2