---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SystemName:
    Type: String
  SGECS:
    Type: String
  ELBTargetGroupArn:
    Type: String
  ECSTaskExecutionRole:
    Type: String
  ECSWordpressTaskRoleArn:
    Type: String
  ECRWordpressRepositoryUri:
    Type: String
  LogsWordpress:
    Type: String
  EFSVolumeWordpress:
    Type: String
Resources:
  BlogECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref SystemName
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 0

  BlogECSWordpressService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: Wordpress
      Cluster: !Ref BlogECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref BlogECSWordpressTaskDefinition
      EnableExecuteCommand: True
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Base: 1
          Weight: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref SGECS
          Subnets:
            - !ImportValue VPC-ProtectedSubnetIdDHCPA
            - !ImportValue VPC-ProtectedSubnetIdDHCPC
            - !ImportValue VPC-ProtectedSubnetIdDHCPD
      LoadBalancers:
        - ContainerName: Wordpress
          ContainerPort: 80
          TargetGroupArn: !Ref ELBTargetGroupArn

  BlogECSWordpressTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${SystemName}-Wordpress
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      TaskRoleArn: !Ref ECSWordpressTaskRoleArn
      ContainerDefinitions:
        - Name: Wordpress
          Image: !Ref ECRWordpressRepositoryUri
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          Secrets:
            - Name: WORDPRESS_DB_HOST
              ValueFrom: /System/Blog/MySQL/HOST
            - Name: WORDPRESS_DB_NAME
              ValueFrom: /System/Blog/MySQL/MYSQL_DATABASE
            - Name: WORDPRESS_DB_USER
              ValueFrom: /System/Blog/MySQL/MYSQL_USER
            - Name: WORDPRESS_DB_PASSWORD
              ValueFrom: /System/Blog/MySQL/MYSQL_PASSWORD
          MountPoints:
            - SourceVolume: Wordpress-Volume
              ContainerPath: "/var/www/html"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogsWordpress
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Volumes:
        - Name: Wordpress-Volume
          EFSVolumeConfiguration:
            FilesystemId: !Ref EFSVolumeWordpress
            TransitEncryption: ENABLED
