---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SGEFS:
    Type: String
  SystemName:
    Type: String
Resources:
  BlogEFSWordpress:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: True
      FileSystemTags:
        - Key: Name
          Value: !Sub ${SystemName}-Wordpress
  BlogEFSWordpressMountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref BlogEFSWordpress
      SecurityGroups:
        - !Ref SGEFS
      SubnetId: !ImportValue VPC-PrivateSubnetIdDHCPA
  BlogEFSWordpressMountTargetC:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref BlogEFSWordpress
      SecurityGroups:
        - !Ref SGEFS
      SubnetId: !ImportValue VPC-PrivateSubnetIdDHCPC
  BlogEFSWordpressMountTargetD:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref BlogEFSWordpress
      SecurityGroups:
        - !Ref SGEFS
      SubnetId: !ImportValue VPC-PrivateSubnetIdDHCPD
Outputs:
  EFSWordpress:
    Value: !Ref BlogEFSWordpress