name: "Run CloudFormation linter"

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint
      - name: Add problem matcher
        run: echo "::add-matcher::.github/cfn-lint.json"
      - name: Lint by cfn-lint
        shell: bash
        run: |
          for STACK_PATH in $(find . -type d -name '.github' -prune -o -name "*.yaml" -type f -print)
          do
            echo "=== ${STACK_PATH} ==="
            cfn-lint ${STACK_PATH} -f parseable && echo "No Error!" || FAILED=$((++FAILED))
          done
          if [ -n ${FAILED} ];
          then
            false
          else
            true
          fi
