---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SystemName:
    Type: String
  SGECS:
    Type: String
  ELBTargetGroupArn:
    Type: String
  ECSTaskExecutionRole:
    Type: String
  ECSTaskRoleArn:
    Type: String
  LogsServer:
    Type: String
  LogsWeb:
    Type: String
  LogsAgent:
    Type: String
  ECRZabbixServerRepositoryUri:
    Type: String
  ECRZabbixWebRepositoryUri:
    Type: String
  ECRZabbixAgentRepositoryUri:
    Type: String
Resources:
  ZabbixECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref SystemName
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 0

  ZabbixECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref SystemName
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      TaskRoleArn: !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: Server
          Image: !Ref ECRZabbixServerRepositoryUri
          Secrets:
            - Name: DB_SERVER_HOST
              ValueFrom: /System/Zabbix/MySQL/HOST
            - Name: MYSQL_USER
              ValueFrom: /System/Zabbix/MySQL/MYSQL_USER
            - Name: MYSQL_PASSWORD
              ValueFrom: /System/Zabbix/MySQL/MYSQL_PASSWORD
            - Name: MYSQL_ROOT_USER
              ValueFrom: /RDS/User/admin
            - Name: MYSQL_ROOT_PASSWORD
              ValueFrom: /RDS/Password/admin
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogsServer
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
        - Name: Web
          Image: !Ref ECRZabbixWebRepositoryUri
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          Environment:
            - Name: ZBX_SERVER_NAME
              Value: zabbix.aws.tencho-lab.net
          Secrets:
            - Name: DB_SERVER_HOST
              ValueFrom: /System/Zabbix/MySQL/HOST
            - Name: MYSQL_USER
              ValueFrom: /System/Zabbix/MySQL/MYSQL_USER
            - Name: MYSQL_PASSWORD
              ValueFrom: /System/Zabbix/MySQL/MYSQL_PASSWORD
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogsWeb
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
        - Name: Agent
          Image: !Ref ECRZabbixAgentRepositoryUri
          Secrets:
            - Name: ZBX_HOSTNAME
              ValueFrom: /System/Zabbix/Server/HOSTNAME
            - Name: ZBX_SERVER_HOST
              ValueFrom: /System/Zabbix/Server/SERVER_HOST
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogsAgent
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ZabbixECSServerService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: Server
      Cluster: !Ref ZabbixECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref ZabbixECSTaskDefinition
      EnableExecuteCommand: True
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Base: 1
          Weight: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref SGECS
          Subnets:
            - !ImportValue VPC-ProtectedSubnetIdDHCPA
            - !ImportValue VPC-ProtectedSubnetIdDHCPC
            - !ImportValue VPC-ProtectedSubnetIdDHCPD
      LoadBalancers:
        - ContainerName: Web
          ContainerPort: 8080
          TargetGroupArn: !Ref ELBTargetGroupArn
      ServiceRegistries:
        - RegistryArn: !GetAtt ZabbixCloudMapServer.Arn
  ZabbixCloudMapServer:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: zabbix-server
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 60
        NamespaceId: !ImportValue CloudMap-NameSpaceId
