---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SystemName:
    Type: String
  FQDN:
    Type: String
Resources:
  ZabbixACM:
    Type: AWS::CertificateManager::Certificate
    Properties:
      Tags:
        - Key: Name
          Value: !Ref SystemName
Outputs:
  CertificateArn:
    Value: !Ref ZabbixACM
    Export:
      Name: System-Zabbix-ACMArn